# Generated by Django 3.2.12 on 2023-10-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20231013_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='color',
        ),
        migrations.RemoveField(
            model_name='peopleaddress',
            name='people',
        ),
        migrations.DeleteModel(
            name='YoutubeVideo',
        ),
        migrations.DeleteModel(
            name='Colors',
        ),
        migrations.DeleteModel(
            name='People',
        ),
        migrations.DeleteModel(
            name='PeopleAddress',
        ),
    ]
