# Generated by Django 3.2.12 on 2023-10-13 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
