# Generated by Django 3.2.12 on 2023-10-13 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_student_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.teacher'),
        ),
    ]
