# Generated by Django 3.2.12 on 2023-10-16 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20231016_0558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='recomendedby',
            new_name='recommendedby',
        ),
        migrations.AlterField(
            model_name='author',
            name='recommendedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_authors', related_query_name='recommended_authors', to='app1.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
