# Generated by Django 3.2.12 on 2023-10-16 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20231016_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
        migrations.RemoveField(
            model_name='books',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='recommendedby',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
