# Generated by Django 3.2.12 on 2023-10-16 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0013_auto_20231016_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('zipcode', models.IntegerField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=100)),
                ('joindate', models.DateField(blank=True)),
                ('popularity_score', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100)),
                ('joindate', models.DateField(blank=True)),
                ('popularity_score', models.IntegerField(blank=True)),
                ('recommendedby', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app1.publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('price', models.IntegerField(blank=True)),
                ('published_date', models.DateField(blank=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', related_query_name='books', to='app1.author')),
                ('publisher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', related_query_name='books', to='app1.publisher')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_authors', related_query_name='followed_authors', to='app1.User'),
        ),
        migrations.AddField(
            model_name='author',
            name='recommendedby',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_authors', related_query_name='recommended_authors', to='app1.author'),
        ),
    ]
