# Generated by Django 3.2.12 on 2023-10-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='recommendedby',
        ),
        migrations.RemoveField(
            model_name='books',
            name='publisher',
        ),
    ]
