# Generated by Django 3.2.12 on 2023-10-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20231016_0627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
