# Generated by Django 3.2.12 on 2023-10-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20231016_0749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
